### ISSUE TITLE
extract_uce_bypass_MGH issue

### ISSUE THREAD

**Issue by emilyostrow** [mgharvey/seqcap_pop#5]
Hi Mike,

When I run your script, I get the following error:

[@submit2 SNP]$ python extract_uce_bypass_MGH.py 
Traceback (most recent call last):
  File "extract_uce_bypass_MGH.py", line 25, in <module>
    from seqtools.sequence import fasta
ImportError: No module named sequence

Is there a dependency issue here? I installed seqtools from Brant's github and installed the dependencies listed for seqtools.

I am using python2.7.13 in a cluster environment. I would appreciate any suggestions. Thanks!

**Comment by stachyris** [comment]
Hey there! @emilyostrow 

Did you figure out this issue? 
I am running into same problem :(

Best, 
Vinay

**Comment by emilyostrow** [comment]
Hi Vinay,


I never got this working. I ended up creating a consensus sequence of each UCE and calling SNPs in gatk with the consensus sequence as the reference, which worked out pretty well. Good luck.
